#!/usr/bin/env zsh
mydir=`dirname $0`
if [[ $mydir = . ]]; then
	mydir=`pwd`
fi
dest=$HOME
echo My Directory: $mydir
cp $HOME/.zshenv $HOME/.zshenv.pre_zshkit
cp $HOME/.zshrc $HOME/.zshrc.pre_zshkit
cp $HOME/.gitconfig $HOME/.gitconfig.pre_zshkit
cp $mydir/default_zshenv $HOME/.zshenv
cp $mydir/default_zshrc $HOME/.zshrc
cp $mydir/default_gitconfig $HOME/.gitconfig
